modLoader = "javafml" #mandatory
loaderVersion = "[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "GNU AGPL 3.0"
[[mods]] #mandatory
modId = "moreleads" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "MoreLeads" #mandatory
logoFile = "logo.png" #optional
authors = "cnlimiter" #optional
description = '''

'''
[[dependencies.moreleads]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[43,)" #mandatory
ordering = "NONE"
side = "SERVER"

